### ISSUE TITLE
See if others have resolved a comment? Or ability to resolve it for everyone?

### ISSUE THREAD

**Issue by henrik** [barsoom/ex-remit#28]
See discussion: https://auctionet.slack.com/archives/CF9SAN79V/p1592900099078400

**Comment by ulfurinn** [comment]
Looks like this calls for adding the `resolved` state to the comment entity itself.

It's possible to solve in SQL without touching the schema ("resolved comment" = "has any resolved notification"), but:
- it would be pretty unwieldy to express in Ecto
- it should be consistent with the "intended recipient" semantics to distinguish between the author group and any random discussion participants, making the expression even more complex
- the "resolve all" functionality, should we decide to add it, would imply acking other people's notifications, which makes little sense

**Comment by henrik** [comment]
I'll close this one – we now (since a good while back) indicate if other pair committers have resolved their comment.
