### ISSUE TITLE
Revisit `@foo Application.get_env(…)` pattern

### ISSUE THREAD

**Issue by henrik** [barsoom/ex-remit#38]
Gets env at compile-time, so maybe not a good choice in some cases, e.g. for API keys. If we e.g. change the Heroku API key, I believe it wouldn't actually change until the next deploy.

**Comment by p-wall** [comment]
https://github.com/Nebo15/confex might help with this

**Comment by henrik** [comment]
This happened – we changed the API key and were confused by it not having effect: https://auctionet.slack.com/archives/CF9SAN79V/p1624961767148600
